# Generated by Django 4.0.3 on 2022-03-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/silder_img')),
                ('DISCOUNT_DEAL', models.CharField(choices=[('HOT DEALS', 'HOT DEALS'), ('New Arraivels', 'New Arraivels')], max_length=1000)),
                ('SALE', models.IntegerField()),
                ('Brand_Name', models.CharField(max_length=2000)),
                ('Discount', models.IntegerField()),
                ('Link', models.CharField(max_length=2000)),
            ],
        ),
    ]
