# Generated by Django 4.0.3 on 2022-03-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/banner_img')),
                ('DISCOUNT_DEAL', models.CharField(max_length=1000)),
                ('Quote', models.CharField(max_length=100)),
                ('Discount', models.IntegerField()),
            ],
        ),
    ]
