# Generated by Django 4.0.3 on 2022-03-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_banner_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner_area',
            old_name='Quote',
            new_name='Quality',
        ),
    ]
