# Generated by Django 4.0.3 on 2022-03-17 20:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_product_section_product_image_product_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Information',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_information',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
